name: texture-env
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.11.17=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.0=pyha63f2e9_0
  - ipython=8.20.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py310h5588dad_0
  - libffi=3.4.4=hd77b12b_0
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.12=h2bbff1b_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py310haa95532_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.10.13=he1021f5_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pywin32=305=py310h2bbff1b_0
  - pyzmq=25.1.2=py310hd77b12b_0
  - setuptools=68.2.2=py310haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py310he2412df_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py310haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - freetype-py==2.4.0
      - idna==3.6
      - imageio==2.33.1
      - networkx==3.2.1
      - numpy==1.26.3
      - pillow==10.2.0
      - pyglet==2.0.10
      - pyopengl==3.1.0
      - pyrender==0.1.45
      - requests==2.31.0
      - scipy==1.12.0
      - trimesh==4.1.3
      - urllib3==2.1.0
prefix: C:\Users\Francesco\miniconda3\envs\texture-env
